version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"                   
    networks:
      - app-network
      

networks:
  app-network:
    driver: bridge

